name: UmeAiRT
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - git
  - cuda-toolkit=12.9
  - pip
  - conda-forge::aria2
  - ninja
  - ccache
  - c-compiler
  - cxx-compiler
