name: UmeAiRT
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12.12
  - git
  - nvidia::cuda-toolkit=13.0.2
  - pip
  - ninja
  - ccache
  - c-compiler
  - cxx-compiler
